using CobsDomain.DslLineStateServiceReference;
using System;
using System.Runtime.Serialization;
using System.ServiceModel;

namespace DomainBellaNS.API
{

    [DataContract]
    public enum DomainError
    {
        [EnumMember]
        DomainError = 1,
        [EnumMember]
        InvalidBundleId,
        [EnumMember]
        InvalidProductId,
        [EnumMember]
        InvalidSubscriptionId,
        [EnumMember]
        ServiceAccountNotFound,
        [EnumMember]
        SubscriptionNotFound,
        [EnumMember]
        CustomerAccountNotFound,
        [EnumMember]
        PropositionNotFound,
        [EnumMember]
        ProductNotFound,
        [EnumMember]
        BundleNotFound,
        [EnumMember]
        InvoiceNotFound,
        [EnumMember]
        AccountIdAlreadyHasCredentials,
        [EnumMember]
        LoginFailed,
        [EnumMember]
        LoginNotFound,
        [EnumMember]
        LoginDuplicate,
        [EnumMember]
        PasswordsDoNotMatch,
        [EnumMember]
        InvalidPassword,
        [EnumMember]
        BundleIdNotFound,
        [EnumMember]
        CustomerAccountAlreadyExists,
        [EnumMember]
        ServiceAccountAlreadyExists,
        [EnumMember]
        InvalidInvoiceId,
        [EnumMember]
        NoServiceAccountsFound,
        [EnumMember]
        NoCustomerAccounts,
        [EnumMember]
        IdValidationError,
        [EnumMember]
        PeriodValidationError,
        [EnumMember]
        EmptyArgument,
        [EnumMember]
        InvalidArgument,
        [EnumMember]
        InvalidOrderState,
        [EnumMember]
        ProductNotMandatory,
        [EnumMember]
        BundleNotMandatory,
        [EnumMember]
        OrderNotFound,
        [EnumMember]
        DuplicateKey,
        [EnumMember]
        InvalidNumberOfEntities,
        [EnumMember]
        SettingNotFound,
        [EnumMember]
        UnexpectedError,
        [EnumMember]
        ValidateOrderError,
        [EnumMember]
        InvalidPropositionId,
        [EnumMember]
        InvalidScore,
        [EnumMember]
        TaskNotFound,
        [EnumMember]
        InvalidOrderStatus,
        [EnumMember]
        ServiceCategoryNotFound,
        [EnumMember]
        VendorNotFound,
        [EnumMember]
        ServiceAccountActivationError,
        [EnumMember]
        ServiceAccountStopError,
        [EnumMember]
        InstallationIsAlreadyRequested,
        [EnumMember]
        OrderIdIsMissed,
        [EnumMember]
        FutureConnectionIdIsNotFound,
        [EnumMember]
        IncorrectServiceAccountState,
        [EnumMember]
        PropositionProlongationIsNotAvailable,
        [EnumMember]
        IncorrectServiceCategory,
        [EnumMember]
        InvalidProcessStep,
        [EnumMember]
        CobsInvalidParameters,
        [EnumMember]
        CobsRetrieveOrderError,
        [EnumMember]
        MandateNotFound,
        [EnumMember]
        FunctionalityIsNotSupported,
        [EnumMember]
        OrderStateNotFound,
        [EnumMember]
        IncorrectProlongationContractDuration,
        [EnumMember]
        CobsPostCodeCheckError,
        [EnumMember]
        TypeOfServiceAlreadyExists,
        [EnumMember]
        TypeOfServiceNotFound,
        [EnumMember]
        IncorrectPropositionId,
        [EnumMember]
        ProductTypeOfServiceDublication,
        [EnumMember]
        EmptyProductCollection,
        [EnumMember]
        PropositionNameAlreadyExists,
        [EnumMember]
        ProductTemplateIsNotFound,
        [EnumMember]
        IncorrectProductTemplateId,
        [EnumMember]
        EmptyProductBundleCollection,
        [EnumMember]
        ProductTemplateNameAlreadyExists,
        [EnumMember]
        ProductBundleDuplication,
        [EnumMember]
        NoInvoicesSelected,
        [EnumMember]
        EmptyInvoiceId,
        [EnumMember]
        InvalidAmount,
        [EnumMember]
        MatchBankTransactionError,
        [EnumMember]
        UnsupportedBankTransactionType,
        [EnumMember]
        InvoiceClearanceFailed,
        [EnumMember]
        AddPaymentToServiceAccountError,
        [EnumMember]
        RemainingPaymentAmountError,
        [EnumMember]
        TransactionNotFound,
        [EnumMember]
        InvalidInvoiceStatus,
        [EnumMember]
        InvoiceItemIsMissing,
        [EnumMember]
        DiscountNotFound,
        [EnumMember]
        BundleWithIncorrectTypeOfServiceId,
        [EnumMember]
        ProductTemplateDeletionIsImpossible,
        [EnumMember]
        PropositionDeletionIsImpossible,
        [EnumMember]
        ProductWithMissingOrderType,
        [EnumMember]
        InvalidProductTemplateId,
        [EnumMember]
        TypeOfServiceIsUsed,
        [EnumMember]
        TaskActionNotFound,
        [EnumMember]
        GenericObjectPassed,
        [EnumMember]
        IncorrectDiscountId,
        [EnumMember]
        IncorrectProductId,
        [EnumMember]
        EmptyOrderTypes,
        [EnumMember]
        InvalidPricePlanId,
        [EnumMember]
        IncorrectPricePlanId,
        [EnumMember]
        IncorrectPriceItemDuration,
        [EnumMember]
        IncorrectPriceItemId,
        [EnumMember]
        InvalidPriceItemDuration,
        [EnumMember]
        InvalidPriceItemVariablePrice,
        [EnumMember]
        InvalidPriceItemSetupPrice,
        [EnumMember]
        InvalidPriceItemBundleId,
        [EnumMember]
        InvalidPriceItemId,
        [EnumMember]
        IncorrectDiscountDuration,
        [EnumMember]
        InvalidDiscountDuration,
        [EnumMember]
        InvalidDiscountAmount,
        [EnumMember]
        InvalidDiscountName,
        [EnumMember]
        InvalidDiscountId,
        [EnumMember]
        NoPriceItemForBundle,
        [EnumMember]
        InvalidPricePlanName,
        [EnumMember]
        InvalidRateClassName,
        [EnumMember]
        ProductOfIncorrectTypeOfService,
        [EnumMember]
        InvalidServiceCategoryId,
        [EnumMember]
        IncorrectDiscountAmount,
        [EnumMember]
        ProductIsUsedInProposition,
        [EnumMember]
        PricePlanIsUsedInProduct,
        [EnumMember]
        StartOnGreaterThanEndOn,
        [EnumMember]
        InvalidSubscribedBundleId,
        [EnumMember]
        IncorrectDate,
        [EnumMember]
        IncorrectOperation,
        [EnumMember]
        CobsOrderUpdateException,
        [EnumMember]
        InvalidTaskRuleCreationRequest,
        [EnumMember]
        ContractSendToCustomerExists,
        [EnumMember]
        ServiceCategoryBankComponentParameter,
        [EnumMember]
        PriceItemDuplication,
        [EnumMember]
        IncorrectBundleId,
        [EnumMember]
        InvalidTypeOfServiceId,
        [EnumMember]
        InvalidPageNumber,
        [EnumMember]
        InvalidPerPage,
        [EnumMember]
        TaskRuleDoesNotExist,
        [EnumMember]
        MandateAlreadyExists,
        [EnumMember]
        IncorrectSequence,
        [EnumMember]
        DuplicateSetting,
        [EnumMember]
        InvalidName,
        [EnumMember]
        InvalidStartOn,
        [EnumMember]
        InvalidEndOn,
        [EnumMember]
        InvalidCreatedOn,
        [EnumMember]
        InvalidCreatedBy,
        [EnumMember]
        InvalidDescription,
        [EnumMember]
        ChangeApplicationLogicNotImplemented,
        [EnumMember]
        TypeOfServiceIdDuplictaion,
        [EnumMember]
        InvalidId,
        [EnumMember]
        IncorrectServiceCategoryId,
        [EnumMember]
        OfferNotFound,
        [EnumMember]
        InvalidCashbackId,
        [EnumMember]
        InvalidCashbackName,
        [EnumMember]
        InvalidCashbackDuration,
        [EnumMember]
        IncorrectCashbackId,
        [EnumMember]
        IncorrectCashbackDuration,
        [EnumMember]
        IncorrectCashbackAmount,
        [EnumMember]
        InvalidCashbackAmount,
        [EnumMember]
        CustomerAccountInBlackList,
        [EnumMember]
        RoleAlreadyExists,
        [EnumMember]
        EmptyRoleName,
        [EnumMember]
        EmptyRolesList,
        [EnumMember]
        EmptyRightsList,
        [EnumMember]
        RoleNotFound,
        [EnumMember]
        AccountNotFound,
        [EnumMember]
        RoleIsAssignedToAccount,
        [EnumMember]
        InvalidReasonCodeId,
        [EnumMember]
        IncorrectReasonCodeId,
        [EnumMember]
        InvalidAccountId,
        [EnumMember]
        InvalidServiceAccountId,
        [EnumMember]
        IncorrectServiceAccountId,
        [EnumMember]
        IncorrectFinancialActionRequestId,
        [EnumMember]
        InvalidFinancialActionRequestId,
        [EnumMember]
        InvalidVerifiedBy,
        [EnumMember]
        IncorrectFinancialActionRequestState,
        [EnumMember]
        FinancialActionRequestConfirmationLogicNotImplemented,
        [EnumMember]
        FinancialActionRequestRejectionLogicNotImplemented,
        [EnumMember]
        IncorrectBankTransactionId,
        [EnumMember]
        IncorrectIban,
        [EnumMember]
        IncorrectCreditTransferId,
        [EnumMember]
        EmptyAccessToken,
        [EnumMember]
        EmptyRefreshToken,
        [EnumMember]
        EmptyAccountId,
        [EnumMember]
        InvalidTokenLifetime,
        [EnumMember]
        CredentialsNotFound,
        [EnumMember]
        AccountIsBlocked,
        [EnumMember]
        SessionNotFound,
        [EnumMember]
        InvalidToken,
        [EnumMember]
        SessionExpired,
        [EnumMember]
        IncorrectManualBalanceCorrectionRequestState,
        [EnumMember]
        InvalidReasonCode,
        [EnumMember]
        IncorrectInvoiceStatus,
        [EnumMember]
        IncorrectManualInvoiceClearanceRequestState,
        [EnumMember]
        IncorrectAmountToMatch,
        [EnumMember]
        InvalidRoleName,
        [EnumMember]
        InvalidCashbackBillPeriodQuantity,
        [EnumMember]
        IncorrectRequestId,
        [EnumMember]
        InvalidBankTransactionId,
        [EnumMember]
        MultipleOverpaidInvoices,
        [EnumMember]
        IncorrectInvoiceId,
        [EnumMember]
        UnknownInvoiceClearanceDetails,
        [EnumMember]
        InvoiceIsAlreadyClearing,
        [EnumMember]
        TaskSkillDoesNotExist,
        [EnumMember]
        EmployeeAlreadyHasSuchSkill,
        [EnumMember]
        InvalidTaskStatus,
        [EnumMember]
        UnsupportedUpdateOrderRequest,
        [EnumMember]
        OverstappenServiceError,
        [EnumMember]
        OverstappenDossierIsNotFound,
        [EnumMember]
        ImpossibleToChangeOrCancelOverstappenRequest,
        [EnumMember]
        ProlongationIsNotAvailable,
        [EnumMember]
        InvalidMailToPayResponse,
        [EnumMember]
        MtpPaymentRequestNotFound,
        [EnumMember]
        IncorrectUncollectableInvoiceClearanceRequestState,
        [EnumMember]
        InvalidDelay,
        [EnumMember]
        GlEventNotFound,
        [EnumMember]
        InvalidGlBalanceId,
        [EnumMember]
        GlAccountNotFound,
        [EnumMember]
        UnknownDunningProcess,
        [EnumMember]
        OrderAlreadyHasAnAssignedCustomer,
        [EnumMember]
        RateClassNotFound,
        [EnumMember]
        InvalidRateClassId,
        [EnumMember]
        InvalidPhoneCode,
        [EnumMember]
        InvalidBundleCoverageSize,
        [EnumMember]
        NoPropositionVendorsSpecified,
        [EnumMember]
        CannotBeSoldByThisVendor,
        [EnumMember]
        SaledateNotValidForThisVendor,
        [EnumMember]
        BundleCoverageAlreadyExists,
        [EnumMember]
        InvalidExcassoReasonId,
        [EnumMember]
        VerifyCreditTransferError,
        [EnumMember]
        IncorrectCreditTransferRequestId,
        [EnumMember]
        IncorrectBankTransactionType,
        [EnumMember]
        IncorrectExcassoAmount,
        [EnumMember]
        InvalidCreditTransferId,
        [EnumMember]
        UnknownTypeOfRegularVirtualBalanceRecord,
        [EnumMember]
        ExcassoBlockExists,
        [EnumMember]
        ExcassoBlockNotFound,
        [EnumMember]
        InvalidExcassoBlockId,
        [EnumMember]
        InvalidExcassoBlockDuration,
        [EnumMember]
        ServiceAccountBlockedForExcasso,
        [EnumMember]
        InvalidExcassoBlockStatus,
        [EnumMember]
        BlockReasonNotFound,
        [EnumMember]
        InvalidCreditRiskLevel,
        [EnumMember]
        InvalidSequenceNumber,
        [EnumMember]
        InvalidBalance,
        [EnumMember]
        CobsMapNotFound,
        [EnumMember]
        OrderTypeViolation,
        [EnumMember]
        ClearanceBlockExists,
        [EnumMember]
        ClearanceBlockNotFound,
        [EnumMember]
        InvoiceClearanceBlocked,
        [EnumMember]
        UnknowCancellationReason,
        [EnumMember]
        InvalidCancellationFeeType,
        [EnumMember]
        InvalidOrderAction,
        [EnumMember]
        ReversalOfRevertedCallDataRecord,
        [EnumMember]
        CreatePaymentArrangementError,
        [EnumMember]
        InvalidPaymentArrangementId,
        [EnumMember]
        InvalidPaymentArrangementStatus,
        [EnumMember]
        InvalidClearanceBlockDuration,
        [EnumMember]
        InvalidDirectDebitBlockDuration,
        [EnumMember]
        DirectDebitBlockExists,
        [EnumMember]
        DirectDebitBlockNotFound,
        [EnumMember]
        InvoiceDirectDebitBlocked,
        [EnumMember]
        DunningProcessNotFound,
        [EnumMember]
        RecreationAlreadyInitiated,
        [EnumMember]
        IncorrectInvoiceType,
        [EnumMember]
        CannotRecreateNonEndNoteInvoiceInDunningWithIncludingUninvoicedVirtualBalanceRecords,
        [EnumMember]
        CannotRecreateInvoiceWithDirectDebitBlock,
        [EnumMember]
        IncorrectStatusOrType,
        [EnumMember]
        RecreationOfUnrespondedInvoice,
        [EnumMember]
        InvoiceWithClearanceBlockRecreation,
        [EnumMember]
        ContractIdIsEmpty,
        [EnumMember]
        ContractNotFound,
        [EnumMember]
        InvalidCreateAdjustingOrderRequest,
        [EnumMember]
        AvailablePropositionNotFound,
        [EnumMember]
        InvalidSubscriptionStatus,
        [EnumMember]
        CannotRecreateInvoiceWithoutNewVirtualBalanceRecords,
        [EnumMember]
        BundleIsNotMonthlyTerminable,
        [EnumMember]
        SubscribedBundleIdsAreNotUnique,
        [EnumMember]
        MoreThanOneIsMainBundle,
        [EnumMember]
        InvalidSubscribeBundleWithDiscountRequest,
        [EnumMember]
        StbNumberExceeded,
        [EnumMember]
        InvalidDslUpgrade,
        [EnumMember]
        DuplicateOrder,
        [EnumMember]
        NoIbanForServiceAccount,
        [EnumMember]
        InvalidRegionRange,
        [EnumMember]
        InvalidInstallationDatesRange,
        [EnumMember]
        InvalidRegionCodeLength,
        [EnumMember]
        RegionNameNotFound,
        [EnumMember]
        RegionNameExists,
        [EnumMember]
        ReginIdNotFound,
        [EnumMember]
        RegionScheduleNotExist,
        [EnumMember]
        RegionScheduleExists,
        [EnumMember]
        InstallationBookItemExists,
        [EnumMember]
        InstallationBookItemNotExist,
        [EnumMember]
        AllInstallationsBooked,
        [EnumMember]
        ServiceAccountAlreadySubscribed,
        [EnumMember]
        ServiceAccountNotSubscribed,
        [EnumMember]
        PendingInstallationRequestExists,
        [EnumMember]
        PendingInstallationRequestNotExist,
        [EnumMember]
        IncorrectBankTransactionState,
        [EnumMember]
        AssignedMailsNotFound,
        [EnumMember]
        AvailableProductNotFound,
        [EnumMember]
        PriceItemNotFound,
        [EnumMember]
        InvalidDunningBlockDuration,
        [EnumMember]
        DunningBlockNotFound,
        [EnumMember]
        AdjustingOrderPipelineFinished,
        [EnumMember]
        ServiceAccountIdIsEmpty,
        [EnumMember]
        RegionCodeExists,
        [EnumMember]
        CodesRangeNotInRegion,
        [EnumMember]
        RegionScheduleDaysExist,
        [EnumMember]
        RegionScheduleDaysNotFound,
        [EnumMember]
        InvalidMaxInstallationCount,
        [EnumMember]
        InvalidPlanninsToolReminderConfiguration,
        [EnumMember]
        WishDateManipulationIsNotPossible,
        [EnumMember]
        OverstappenDonorProcessIsNotOverdueYet,
        [EnumMember]
        CallDataRecordNotFound,
        [EnumMember]
        VideoOnDemandNotFound,
        [EnumMember]
        PqccCheckResultInfoForOrderNotFound
    }

    namespace CobsService
    {

    }


    [DataContractAttribute]
    public class DomainFault
    {
        [DataMemberAttribute]
        public DomainError Code;

        [DataMemberAttribute]
        public string Message;
    }
}
